#!/usr/bin/env python
# TODO: load module passed by commandline

print "SHR: initializing..."
import e_dbus, dbus, elementary
print "SHR: import"
from shr_settings_modules import shr_pim

def close(obj, event, *args, **kargs):
    print "SHR: stopUpdate"
    mod.stopUpdate()
    print "SHR: destroy"
    mod.destroy()
    print "SHR: closing..."
    elementary.exit()

elementary.init()
mainloop = e_dbus.DBusEcoreMainLoop()
bus = dbus.SystemBus(mainloop=mainloop)
win = elementary.Window("lol", elementary.ELM_WIN_BASIC)
win.show()
bg = elementary.Background(win)
win.resize_object_add(bg)
bg.show()

print "SHR: constructor"
mod = shr_pim.Pim(win, bus)
print "SHR: isEnabled"
print "SHR: enabled = "+str(mod.isEnabled())
print "SHR: createView"
view = mod.createView()
scroll = elementary.Scroller(win)
win.resize_object_add(scroll)
scroll.show()

frame = elementary.Frame(win)
frame.label_set(mod.getName())
frame.content_set(view)
frame.show()

frame.size_hint_weight_set(1.0, 0.0)

scroll.content_set(frame)

view.size_hint_align_set(-1.0, -1.0)
view.size_hint_weight_set(1.0, 0.0)
view.show()
win.destroy = close

elementary.run()
elementary.shutdown()
